---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: reduce-snapshot
  annotations:
    tekton.dev/pipelines.minVersion: 0.0.1
    tekton.dev/tags: konflux
  labels:
    app.kubernetes.io/version: "0.1"
    build.appstudio.redhat.com/build_type: docker
spec:
  description: Reduce a snapshot to contain the single component that the snapshot was created for.
  params:
    - name: SNAPSHOT
      description: Snapshot to possibly reduce
      type: string
    - name: REDUCE_SNAPSHOT
      description: Reduce the Snapshot to only the component whose build caused the Snapshot to be created
      type: string
      default: false
    - name: PIPELINERUN_ID
      description: Name of current PipelineRun.
      type: string
  results:
    - name: SNAPSHOT
      description: Reduced Snapshot if REDUCE == true otherwise the original Snapshot
  steps:
    - name: reduce-snapshot
      image: quay.io/konflux-ci/appstudio-utils:ab6b0b8e40e440158e7288c73aff1cf83a2cc8a9@sha256:24179f0efd06c65d16868c2d7eb82573cce8e43533de6cea14fec3b7446e0b14
      env:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
        - name: REDUCE_SNAPSHOT
          value: $(params.REDUCE_SNAPSHOT)
        - name: PIPELINERUN_ID
          value: $(params.PIPELINERUN_ID)
      script: |
        set -eu
        set -o pipefail

        echo "Reduce Snapshot? $REDUCE_SNAPSHOT"
        if [ "${REDUCE_SNAPSHOT}" == "true" ]; then
          SNAPSHOT_CREATION_TYPE=$(oc get pr/$PIPELINERUN_ID -ojson | jq -rec '.metadata.labels."test.appstudio.openshift.io/type" // ""')
          SNAPSHOT_CREATION_COMPONENT=$(oc get pr/$PIPELINERUN_ID -ojson | jq -rec '.metadata.labels."appstudio.openshift.io/component" // ""')
  
          echo "SNAPSHOT_CREATION_TYPE: ${SNAPSHOT_CREATION_TYPE}"
          echo "SNAPSHOT_CREATION_COMPONENT: ${SNAPSHOT_CREATION_COMPONENT}"
          if [ "${SNAPSHOT_CREATION_TYPE}" == "component" ] && [ "${SNAPSHOT_CREATION_COMPONENT}" != "" ]; then
            echo "Reduce Snapshot is ${REDUCE_SNAPSHOT} and Snapshot type is component"
            REDUCED_SNAPSHOT=$(echo "${SNAPSHOT}" | jq --arg component "${SNAPSHOT_CREATION_COMPONENT}" \
                'del(.components[] | select(.name != $component))')
            echo "Reducing Snapshot to:"
            echo "$REDUCED_SNAPSHOT" | jq .
            SNAPSHOT=$(echo "$REDUCED_SNAPSHOT" | tr -d ' ' | tr -d '\n')
          fi
        fi
        
        echo "$SNAPSHOT" | tee -a $(results.SNAPSHOT.path)
